import SideMenuComponent from "@/components/SideMenuComponent";
import "./globals.css";

export const metadata = {
  title: "Admin panel",
  description: "Generated by create next app",
};

const SideMenuLayout = ({ children }) => {
  const authenticated = false;

  return (
    <html>
      <body>
        <div className="flex">
          {authenticated && <SideMenuComponent />}
          {children}
        </div>
      </body>
    </html>
  );
};

export default SideMenuLayout;
